class EnvaultError(Exception): ...
class DetectionError(EnvaultError): ...
class VaultError(EnvaultError): ...
class RestoreError(VaultError): ...
class VaultSerializationError(VaultError): ...
class ConfigurationError(EnvaultError): ...
class DependencyError(EnvaultError): ...
